const LOGIN_FORM_VALIDATOR_SETTINGS = {
  form: document.forms.login,
};
const REGISTRATRATION_FORM_VALIDATOR_SETTINGS = {
  form: document.forms.registration,
};

export { LOGIN_FORM_VALIDATOR_SETTINGS, REGISTRATRATION_FORM_VALIDATOR_SETTINGS };
